<Project>
  <PropertyGroup>
    <PetServiceMakeZip>false</PetServiceMakeZip>
    <PetServiceMakeZip Condition="'$(Configuration)' == 'Release'">true</PetServiceMakeZip>
  </PropertyGroup>
  <Target Name="PackagePetService" AfterTargets="Build">
    <DalamudPackager ProjectDir="$(ProjectDir)"
                    OutputPath="$(OutputPath)"
                    AssemblyName="$(AssemblyName)"
                    MakeZip="$(PetServiceMakeZip)"
                    HandleImages="false"
                    Include="$(AssemblyName).dll;$(AssemblyName).deps.json;$(AssemblyName).json;LICENSE.md;images/icon.png"
                    Author="$(Author)"
                    Name="$(Name)"
                    MinimumDalamudVersion="$(MinimumDalamudVersion)"
                    Punchline="$(Punchline)"
                    Description="$(Description)"
                    ApplicableVersion="$(ApplicableVersion)"
                    RepoUrl="$(RepoUrl)"
                    Tags="$(Tags)"
                    CategoryTags="$(CategoryTags)"
                    DalamudApiLevel="$(DalamudApiLevel)"
                    LoadRequiredState="$(LoadRequiredState)"
                    LoadSync="$(LoadSync)"
                    CanUnloadAsync="$(CanUnloadAsync)"
                    LoadPriority="$(LoadPriority)"
                    ImageUrls="$(ImageUrls)"
                    IconUrl="$(IconUrl)"
                    Changelog="$(Changelog)"
                    AcceptsFeedback="$(AcceptsFeedback)"
                    FeedbackMessage="$(FeedbackMessage)" />
  </Target>
</Project>
