using System.Numerics;
using System.Text.Json;
using Dalamud.Bindings.ImGui;
using Dalamud.Interface.ImGuiFileDialog;
using Dalamud.Interface.Textures;
using PetService.Core;
namespace PetService.Windows;
internal sealed class FeaturePortalView:IDisposable
{
 private string petName="",name="",theme="#baa0ff",title="",colour="#ffffff",glow="",target="",moodle="",preset="",query="",bag="",inventoryCharacter="",taskId="",taskTitle="",taskDescription="",due="",checklist="",ledgerNote="",reminderId="",label="",time="18:00";
 private string identityBaseline="",previewDetail="";private readonly Dictionary<string,string> reviewNotes=[];
 private bool useName,prefix,review,reply,resolves=true,enabled=true;private int lockMinutes,moodleMinutes,rewardPoints,priorityIndex,repeatIndex,stacks;private readonly List<ResponseOption> options=[];
 private readonly FileDialogManager dialog=new();private readonly PortraitView portrait=new();private string? portraitData;private bool removePortrait;private string error="";
 internal bool EditingText{get;private set;}
 internal string InventoryCharacter=>inventoryCharacter;internal string IntegrationCharacter=>target;
 private void Input(string label,ref string value,int max=1000){ImGui.InputText(label,ref value,max);EditingText|=ImGui.IsItemActive();}
 private void Action(MasterPortalSession s,string action,object data,bool global=false)=>s.Action(new(){Action=action,Pet=global?null:s.Selected,Data=data});
 internal void Begin(MasterPortalSession s){EditingText=false;dialog.Draw();if(s.Selected==petName)return;petName=s.Selected;ResetPetDrafts();}
 private void ResetPetDrafts(){reminderId=taskId=label=taskTitle=taskDescription=due=checklist=ledgerNote=title=moodle=preset=query=inventoryCharacter=bag=target=previewDetail="";options.Clear();reviewNotes.Clear();time="18:00";reply=review=prefix=false;resolves=enabled=true;lockMinutes=moodleMinutes=rewardPoints=priorityIndex=repeatIndex=stacks=0;colour="#ffffff";glow="";}
 internal void Completed(AdminAction action){if(action.Action=="identity"){portraitData=null;removePortrait=false;identityBaseline="";portrait.ResetPreview();}}
 internal void Identity(MasterPortalSession s){Style.Title("Master identity","One display setting for all linked pets and characters");var current=s.Dashboard!.Identity;var draft=JsonSerializer.Serialize(new{name,useName,theme});if(identityBaseline.Length==0||draft==identityBaseline){name=current.DisplayName;useName=current.UseName;theme=current.Theme;identityBaseline=JsonSerializer.Serialize(new{name,useName,theme});}Input("Display name",ref name,80);ImGui.Checkbox("Display my name instead of Master",ref useName);Input("Theme colour (#RRGGBB)",ref theme,7);ImGui.TextUnformatted("Pet-facing preview: Message from "+(useName?name:"Master"));if(!removePortrait)portrait.Set(current.PortraitRevision,s.Portrait);portrait.Draw();
  if(ImGui.Button("Choose portrait PNG…"))dialog.OpenFileDialog("Master portrait",".png",(ok,path)=>{if(!ok)return;try{var info=new FileInfo(path);if(info.Length>2000000)throw new InvalidOperationException();var bytes=File.ReadAllBytes(path);portraitData=Convert.ToBase64String(bytes);removePortrait=false;portrait.Preview(bytes);error="";}catch{error="Choose a PNG no larger than 2 MB.";}});ImGui.SameLine();if(ImGui.Button("Remove portrait")){removePortrait=true;portraitData=null;portrait.Dispose();}ImGui.TextWrapped(error);
  ImGui.BeginDisabled(useName&&string.IsNullOrWhiteSpace(name));if(ImGui.Button("Save Master identity",new Vector2(-1,40))){Action(s,"identity",new{displayName=name,useName,theme,portrait=portraitData,removePortrait},true);}ImGui.EndDisabled();
 }
 internal void Controls(MasterPortalSession s,AdminPet p){Style.Title("Gameplay lock","Keep the game view visible and native chat usable");var l=p.Features.Lock;ImGui.TextWrapped("State: "+(l?.State??"released")+(l?.Detail.Length>0?" · "+l.Detail:""));Style.Metric("Time remaining",ControlPresentation.Remaining(l,s.Now),"lockremaining");ImGui.InputInt("Duration minutes (0 = until released)",ref lockMinutes);ImGui.BeginDisabled(Paused(p)||lockMinutes is <0 or >10080);if(ImGui.Button("Block gameplay",new Vector2(210,40)))Action(s,"lock",new{enabled=true,minutes=lockMinutes});ImGui.EndDisabled();ImGui.SameLine();if(ImGui.Button("Release gameplay",new Vector2(210,40)))Action(s,"lock",new{enabled=false,minutes=0});ImGui.TextWrapped("The pet's kill switch and safe release remain available. Game activity continues while input is blocked.");
  if(ImGui.CollapsingHeader("Control history")){var records=p.Features.ControlHistory.Concat(s.OlderControlHistory).DistinctBy(x=>x.Id);foreach(var e in records){ImGui.TextWrapped(Local(e.AtUtc)+" · "+e.Kind+" / "+e.Operation+" · "+e.State);if(e.Detail.Length>0)ImGui.TextWrapped(e.Detail);if(e.State=="requested")ImGui.TextUnformatted(e.DurationMinutes>0?$"Duration: {e.DurationMinutes} minutes":e.Kind=="lock"&&e.Operation=="enable"?"Until released":"");}var cursor=s.OlderControlHistory.Count==0?p.Features.ControlHistoryCursor:s.ControlCursor;ImGui.BeginDisabled(s.Busy||string.IsNullOrEmpty(cursor));if(ImGui.Button("Load older control history"))s.LoadOlderControls();ImGui.EndDisabled();}}

 internal static bool Paused(AdminPet p)=>p.Features.Presence.State is "unapproved" or "paused" or "waiting";
 internal void Reminders(MasterPortalSession s,AdminPet p){Style.Title("Daily reminders","All response buttons are chosen by you");foreach(var r in p.Reminders){ImGui.PushID(r.Id);ImGui.TextWrapped(r.Label+" · "+LocalClock.ScheduleTime(r.Time,r.TimeZone,r.NextDueAtUtc,s.Now)+" · your local time · "+(r.Enabled?"Enabled":"Disabled"));if(r.Responses is null)ImGui.TextColored(Style.Accent,"Response setup required");if(ImGui.Button("Edit")){previewDetail="";reminderId=r.Id;label=r.Label;time=LocalClock.ScheduleTime(r.Time,r.TimeZone,r.NextDueAtUtc,s.Now);enabled=r.Enabled;options.Clear();if(r.Responses is { } v){options.AddRange(JsonSerializer.Deserialize<List<ResponseOption>>(JsonSerializer.Serialize(v.Options,ServiceClient.Json),ServiceClient.Json)!);reply=v.AllowReply;resolves=v.ReplyResolves;}else reply=false;}ImGui.SameLine();if(ImGui.Button("Disable"))s.Action(new(){Action="disableReminder",Pet=p.Name,ReminderId=r.Id});ImGui.PopID();}
  ImGui.Separator();if(ImGui.Button("New reminder")){previewDetail="";reminderId="";label="";time="18:00";options.Clear();reply=false;enabled=true;}Input("Label",ref label,160);Input("Your daily time (HH:mm)",ref time,5);ImGui.Checkbox("Enabled",ref enabled);
  for(var i=0;i<options.Count;i++){var o=options[i];ImGui.PushID(o.Id);var ol=o.Label;Input("Button label",ref ol,80);o.Label=ol;var text=o.Text;Input("Returned text",ref text,1000);o.Text=text;if(ImGui.BeginCombo("Action",o.Action)){foreach(var action in new[]{"complete","decline","response","snooze","random-snooze"})if(ImGui.Selectable(action,o.Action==action)){o.Action=action;if(action!="snooze")o.Minutes=null;o.Resolves=action is "complete" or "decline";}ImGui.EndCombo();}if(o.Action=="snooze"){var presetMinutes=o.Minutes??0;if(ImGui.InputInt("Fixed minutes (0 = pet chooses)",ref presetMinutes))o.Minutes=Math.Clamp(presetMinutes,0,10);}
   if(o.Action=="response"){var done=o.Resolves;if(ImGui.Checkbox("Resolve reminder",ref done))o.Resolves=done;}if(ImGui.SmallButton("Remove")){options.RemoveAt(i);ImGui.PopID();break;}ImGui.SameLine();if(i>0&&ImGui.SmallButton("Move up")){(options[i-1],options[i])=(options[i],options[i-1]);ImGui.PopID();break;}ImGui.Separator();ImGui.PopID();}
  if(options.Count<32&&ImGui.Button("Add response button"))options.Add(new());ImGui.Checkbox("Allow a written reply",ref reply);if(reply)ImGui.Checkbox("Written reply resolves reminder",ref resolves);
  var config=new ResponseOptions{Options=options,AllowReply=reply,ReplyResolves=resolves};
  if(ImGui.CollapsingHeader("Preview daily reminder")){ImGui.TextColored(Style.Accent,"Daily reminder");ImGui.TextWrapped(label.Length>0?label:"Your reminder text");ImGui.TextUnformatted(time+" · your local time");ImGui.TextWrapped("Preview only. Click a button to see its behavior; nothing is sent.");foreach(var o in options){if(Style.LiteralButton(o.Label.Length>0?o.Label:"(Empty label)","preview"+o.Id,new Vector2(-1,32)))previewDetail=ControlPresentation.Response(o)+(o.Text.Length>0?" Returned text: "+o.Text:"");ImGui.TextWrapped(ControlPresentation.Response(o));}if(reply){ImGui.TextUnformatted("Written reply field");if(ImGui.Button("Preview written reply"))previewDetail=resolves?"Reports the written reply and closes this occurrence.":"Reports the written reply and leaves this occurrence open.";}ImGui.TextWrapped(previewDetail);if(!config.Usable)ImGui.TextColored(Style.Accent,"Add a response or written reply before enabling.");}
ImGui.TextWrapped("Chosen and random snooze use 1–10 minutes. Random time is shown only to you.");ImGui.BeginDisabled(enabled&&!config.Usable||options.Any(o=>string.IsNullOrWhiteSpace(o.Label))||string.IsNullOrWhiteSpace(label)||!MasterPortalPolicy.ValidTime(time));if(ImGui.Button("Save daily reminder",new Vector2(-1,40)))Action(s,"reminder",new{id=reminderId.Length>0?reminderId:null,label,time,timeZone=LocalClock.ZoneId,enabled,responses=config});ImGui.EndDisabled();
 }
 internal void Inventory(MasterPortalSession s,AdminPet p){Style.Title("Inventory and gil","Last observed contents by character");if(p.Features.SnapshotIssues.TryGetValue("inventory",out var inventoryIssue))ImGui.TextWrapped("Latest inventory upload was rejected ("+inventoryIssue+"). Any contents below are from the last accepted report.");ImGui.BeginDisabled(Paused(p));if(ImGui.Button("Request fresh inventory",new Vector2(230,42)))Action(s,"inventory",new{});ImGui.EndDisabled();if(p.Features.Inventory.Count==0){ImGui.TextWrapped("No inventory snapshot yet. Open the relevant containers on the pet's allowed character.");return;}
  if(ImGui.BeginCombo("Inventory character",inventoryCharacter)){foreach(var x in p.Features.Inventory)if(ImGui.Selectable(x.CharacterName+" @ "+x.HomeWorld,x.CharacterId==inventoryCharacter)){inventoryCharacter=x.CharacterId;bag="";}ImGui.EndCombo();}var snapshot=p.Features.Inventory.FirstOrDefault(x=>x.CharacterId==inventoryCharacter)??p.Features.Inventory[0];inventoryCharacter=snapshot.CharacterId;if(!snapshot.Loaded){ImGui.TextWrapped("Loading this character’s inventory…");return;}Style.Metric("Total gil",snapshot.Gil.ToString("N0"),"gil");ImGui.TextWrapped("Captured "+Local(snapshot.CapturedAtUtc)+(DateTimeOffset.TryParse(snapshot.CapturedAtUtc,out var at)&&(s.Now-at).TotalSeconds>45?" · Last observed":" · Recent"));Input("Find item",ref query,200);
  if(ImGui.BeginCombo("Container",bag)){foreach(var b in snapshot.Containers)if(ImGui.Selectable(b.Name,b.Id==bag))bag=b.Id;ImGui.EndCombo();}if(snapshot.Containers.Count==0){ImGui.TextWrapped("No loaded containers in this snapshot.");return;}var container=snapshot.Containers.FirstOrDefault(x=>x.Id==bag)??snapshot.Containers[0];bag=container.Id;if(container.CapturedAtUtc is not null)ImGui.TextWrapped("Container observed "+Local(container.CapturedAtUtc));if(!container.Available){ImGui.TextWrapped("This container was not loaded at capture.");return;}var used=container.Slots.Count(x=>x.ItemId!=0);ImGui.TextUnformatted($"{used} occupied · {container.Capacity-used} free · Slot numbers start at 1");if(ImGui.BeginTable("inventorygrid",5,ImGuiTableFlags.SizingStretchSame)){foreach(var item in container.Slots){ImGui.TableNextColumn();ImGui.PushID(item.Slot);var match=query.Length==0||item.Name.Contains(query,StringComparison.OrdinalIgnoreCase);if(!match)ImGui.PushStyleVar(ImGuiStyleVar.Alpha,.25f);var texture=item.IconId==0?null:Plugin.Textures.GetFromGameIcon(new GameIconLookup(item.IconId,item.Hq)).GetWrapOrDefault();if(texture is not null)ImGui.Image(texture.Handle,new Vector2(42));else ImGui.Button("—",new Vector2(42));if(ImGui.IsItemHovered()){ImGui.BeginTooltip();ImGui.TextUnformatted($"Slot {item.Slot}: {(item.ItemId==0?"Empty":item.Name+(item.Hq?" HQ":""))}");ImGui.TextUnformatted("Quantity: "+item.Quantity);ImGui.EndTooltip();}ImGui.TextUnformatted(item.Slot+" · "+(item.ItemId==0?"Empty":item.Quantity.ToString()));if(!match)ImGui.PopStyleVar();ImGui.PopID();}ImGui.EndTable();}
 }
 internal void Tasks(MasterPortalSession s,AdminPet p){Style.Title("Tasks","Assignments, submissions and review");Input("Title",ref taskTitle,160);ImGui.InputTextMultiline("Description",ref taskDescription,3000,new Vector2(-1,80));EditingText|=ImGui.IsItemActive();Input("Due on your clock (yyyy-MM-dd HH:mm, blank = none)",ref due,24);var dueValid=LocalClock.TryInput(due,out var dueUtc);if(!dueValid)ImGui.TextColored(Style.Accent,"Enter a local date and time as yyyy-MM-dd HH:mm.");ImGui.TextUnformatted("Checklist (one item per line)");ImGui.InputTextMultiline("##taskchecklist",ref checklist,8040,new Vector2(-1,100));EditingText|=ImGui.IsItemActive();ImGui.Combo("Priority",ref priorityIndex,new[]{"low","normal","high"},3);ImGui.Combo("Repeat",ref repeatIndex,new[]{"none","daily","weekly"},3);ImGui.Checkbox("Require Master review",ref review);ImGui.BeginDisabled(string.IsNullOrWhiteSpace(taskTitle)||!dueValid);if(ImGui.Button("Save assignment"))Action(s,"task",new{id=taskId.Length>0?taskId:null,title=taskTitle,description=taskDescription,dueAtUtc=dueUtc,timeZone=LocalClock.ZoneId,priority=new[]{"low","normal","high"}[priorityIndex],repeat=new[]{"none","daily","weekly"}[repeatIndex],requireReview=review,checklist=checklist.Split('\n',StringSplitOptions.RemoveEmptyEntries).ToList()});ImGui.EndDisabled();ImGui.SameLine();if(ImGui.Button("New task")){taskId=taskTitle=taskDescription=due=checklist="";}
  foreach(var t in p.Features.Tasks){ImGui.PushID(t.Id);ImGui.Separator();ImGui.TextColored(Style.Accent,t.Title+" · "+t.State+(t.DueAtUtc is not null&&LocalState.Parse(t.DueAtUtc)<s.Now&&t.State is not("completed"or"cancelled")?" · Overdue":""));if(t.DueAtUtc is not null)ImGui.TextWrapped("Due "+Local(t.DueAtUtc));ImGui.TextWrapped(t.Description);ImGui.TextWrapped(t.Comment);if(ImGui.Button("Edit")){taskId=t.Id;taskTitle=t.Title;taskDescription=t.Description;due=LocalClock.Input(t.DueAtUtc);checklist=string.Join('\n',t.Checklist.Select(x=>x.Text));review=t.RequireReview;priorityIndex=Array.IndexOf(new[]{"low","normal","high"},t.Priority);repeatIndex=Array.IndexOf(new[]{"none","daily","weekly"},t.Repeat);}var taskNote=reviewNotes.GetValueOrDefault(t.Id)??"";Input("Review note",ref taskNote);reviewNotes[t.Id]=taskNote;if(ImGui.Button("Approve"))Action(s,"taskReview",new{id=t.Id,state="completed",comment=taskNote});ImGui.SameLine();if(ImGui.Button("Return for changes"))Action(s,"taskReview",new{id=t.Id,state="pending",comment=taskNote});ImGui.SameLine();if(ImGui.Button("Cancel task"))Action(s,"taskReview",new{id=t.Id,state="cancelled",comment=taskNote});if(ImGui.CollapsingHeader("Task history"))foreach(var h in t.History)ImGui.TextWrapped(Local(h.AtUtc)+" · "+h.State+" · "+h.Comment);ImGui.PopID();}
 }
 internal void Integrations(MasterPortalSession s,AdminPet p){Style.Title("Honorific and Moodles","Compatible plugins and their local permissions are required");if(p.Features.SnapshotIssues.TryGetValue("catalog",out var catalogIssue))ImGui.TextWrapped("Latest integration catalog was rejected ("+catalogIssue+"). Request a fresh report after correcting it.");if(ImGui.BeginCombo("Approved character",target)){foreach(var c in p.Features.Characters)if(ImGui.Selectable(c.Name+" @ "+c.HomeWorld,c.Id==target))target=c.Id;ImGui.EndCombo();}var chosenCatalog=p.Features.Catalogs.FirstOrDefault(x=>x.TryGetProperty("characterId",out var id)&&id.GetString()==target);JsonElement? catalog=chosenCatalog.ValueKind==JsonValueKind.Object?chosenCatalog:p.Features.Catalog;if(catalog is {ValueKind:JsonValueKind.Object} catalogData && catalogData.TryGetProperty("characterId",out var charId) && charId.GetString()==target) {
   if(catalogData.TryGetProperty("honorific",out var h)){ImGui.TextUnformatted("Honorific: "+(h.TryGetProperty("available",out var ha)&&ha.GetBoolean()?"Available":"Unavailable"));if(h.TryGetProperty("titles",out var titles)&&ImGui.BeginCombo("Saved title",title)){foreach(var t in titles.EnumerateArray()){var text=t.GetProperty("title").GetString()??"";if(ImGui.Selectable(text,title==text)){title=text;prefix=t.TryGetProperty("prefix",out var tp)&&tp.GetBoolean();if(t.TryGetProperty("colour",out var tc)&&tc.ValueKind==JsonValueKind.String)colour=tc.GetString() is {Length:7} savedColour?savedColour:"#ffffff";if(t.TryGetProperty("glow",out var tg)&&tg.ValueKind==JsonValueKind.String)glow=tg.GetString()??"";}}ImGui.EndCombo();}}
   if(catalogData.TryGetProperty("moodles",out var m)){ImGui.TextUnformatted("Moodles: "+(m.TryGetProperty("available",out var ma)&&ma.GetBoolean()?"Available":"Unavailable"));foreach(var kind in new[]{"statuses","presets"})if(m.TryGetProperty(kind,out var choices)&&ImGui.BeginCombo(kind=="statuses"?"Saved Moodle":"Saved preset",kind=="statuses"?moodle:preset)){foreach(var x in choices.EnumerateArray()){var id=x.GetProperty("id").GetString()??"";var text=x.GetProperty("title").GetString()??"";var restricted=x.TryGetProperty("removable",out var removable)&&!removable.GetBoolean();if(ImGui.Selectable(text+(restricted?" · Restricted":""),id==(kind=="statuses"?moodle:preset))){if(kind=="statuses")moodle=id;else preset=id;}}ImGui.EndCombo();}if(m.TryGetProperty("statuses",out var previews)){foreach(var x in previews.EnumerateArray().Where(x=>x.GetProperty("id").GetString()==moodle))MoodlePreview(x);if(m.TryGetProperty("presets",out var presets)){var chosen=presets.EnumerateArray().FirstOrDefault(x=>x.GetProperty("id").GetString()==preset);if(chosen.ValueKind==JsonValueKind.Object&&chosen.TryGetProperty("statuses",out var ids)){ImGui.TextUnformatted("Preset preview");foreach(var x in previews.EnumerateArray().Where(x=>ids.EnumerateArray().Any(id=>id.GetString()==x.GetProperty("id").GetString())))MoodlePreview(x);}}}if(m.TryGetProperty("current",out var states)){ImGui.TextUnformatted("Current statuses");foreach(var state in states.EnumerateArray())MoodlePreview(state);}
}
  }else ImGui.TextWrapped("No catalog for this character. Log in on it and request a fresh report.");Input("Honorific title",ref title,200);Input("Title colour (#RRGGBB)",ref colour,7);Input("Title glow (#RRGGBB or blank)",ref glow,7);ImGui.Checkbox("Title before character name",ref prefix);ImGui.BeginDisabled(Paused(p)||target.Length==0);if(ImGui.Button("Set Honorific"))Action(s,"honorific",new{characterId=target,operation="set",title,colour,glow,prefix});ImGui.SameLine();if(ImGui.Button("Clear PetService title"))Action(s,"honorific",new{characterId=target,operation="clear"});Input("Moodle status GUID",ref moodle,36);Input("Moodles preset GUID",ref preset,36);ImGui.InputInt("Moodle duration minutes (0 = configured)",ref moodleMinutes);ImGui.InputInt("Moodle stacks (0 = configured)",ref stacks);if(ImGui.Button("Apply status"))Action(s,"moodles",new{characterId=target,operation="apply",statusId=moodle,durationMinutes=moodleMinutes,stacks=stacks>0?(int?)stacks:null});ImGui.SameLine();if(ImGui.Button("Remove managed status"))Action(s,"moodles",new{characterId=target,operation="remove",statusId=moodle});if(ImGui.Button("Apply preset statuses"))Action(s,"moodles",new{characterId=target,operation="preset",preset,durationMinutes=moodleMinutes,stacks=stacks>0?(int?)stacks:null});if(ImGui.Button("Clear all PetService-managed statuses"))Action(s,"moodles",new{characterId=target,operation="clear"});ImGui.EndDisabled();foreach(var cmd in p.Features.IntegrationCommands.TakeLast(30))ImGui.TextWrapped(cmd.Kind+" · "+cmd.State+(cmd.Detail.Length>0?" · "+cmd.Detail:""));}
 private static void MoodlePreview(JsonElement x){var icon=x.TryGetProperty("iconId",out var id)&&id.TryGetUInt32(out var n)?n:0;var texture=icon>0?Plugin.Textures.GetFromGameIcon(new GameIconLookup(icon)).GetWrapOrDefault():null;if(texture is not null){ImGui.Image(texture.Handle,new Vector2(40));ImGui.SameLine();}ImGui.TextWrapped((x.TryGetProperty("title",out var title)?title.GetString():"")+(x.TryGetProperty("stacks",out var stacks)?" · Stacks "+stacks:""));if(x.TryGetProperty("description",out var d)&&d.ValueKind==JsonValueKind.String)ImGui.TextWrapped(d.GetString()??"");}
 internal void Rewards(MasterPortalSession s,AdminPet p){var r=p.Features.Rewards;Style.Title("Reward ledger","Optional points recorded by the Master");var on=r.Enabled;if(ImGui.Checkbox("Enable reward ledger",ref on))Action(s,"rewards",new{enabled=on});ImGui.TextUnformatted("Balance: "+r.Balance);ImGui.InputInt("Points to add or spend",ref rewardPoints);Input("Ledger note",ref ledgerNote,200);if(ImGui.Button("Record points"))Action(s,"rewards",new{points=rewardPoints,note=ledgerNote});foreach(var e in r.Entries.Take(50))ImGui.TextWrapped(Local(e.AtUtc)+" · "+e.Points+" · "+e.Note);}
 private static string Local(string value)=>DateTimeOffset.TryParse(value,out var d)?d.ToLocalTime().ToString("g"):"—";
 internal void Clear(){petName="";ResetPetDrafts();dialog.Reset();portrait.Dispose();portraitData=null;removePortrait=false;name="";useName=false;identityBaseline="";}
 public void Dispose()=>Clear();
}
