using System.Numerics;
using Dalamud.Bindings.ImGui;
using PetService.Core;
namespace PetService.Windows;
internal sealed class PetFeatureView(Plugin plugin):IDisposable
{
 private string confirmCharacter="";private bool confirmAllow;private readonly Dictionary<string,TaskDraft> drafts=[];private readonly PortraitView portrait=new();
 internal bool EditingText{get;private set;}
 internal void Home(){if(plugin.SharingAllowed){portrait.Set(plugin.Configuration.Features.Identity.PortraitRevision,plugin.ReadPortrait);portrait.Draw(160);}Style.Title(plugin.MasterName,"Your connection home");var ledger=plugin.Configuration.Features.Rewards;if(ledger.Enabled)Style.Metric("Your rewards",ledger.Balance.ToString(),"petrewards");}
 internal void Characters(){Style.Title("Characters","Choose which characters can share this connection");foreach(var c in plugin.Configuration.Characters){ImGui.PushID(c.Id);var allow=c.Allowed;var current=c.Id==plugin.CurrentCharacterId;ImGui.TextUnformatted(c.Name+" @ "+c.HomeWorld+(current?" · Current":""));if(ImGui.Checkbox("Allow access",ref allow)){confirmCharacter=c.Id;confirmAllow=allow;ImGui.OpenPopup("Confirm character access###access");}var open=true;if(ImGui.BeginPopupModal("Confirm character access###access",ref open,ImGuiWindowFlags.AlwaysAutoResize)){ImGui.TextWrapped(confirmAllow?$"Enable this character for sharing and {plugin.MasterName} controls? You can pause or remove access at any time.":$"Remove access for this character? All {plugin.MasterName} effects and sharing pause while it is active.");if(ImGui.Button(confirmAllow?"Allow access":"Remove access")){plugin.SetCharacterAccess(confirmCharacter,confirmAllow);ImGui.CloseCurrentPopup();}ImGui.SameLine();if(ImGui.Button("Cancel"))ImGui.CloseCurrentPopup();ImGui.EndPopup();}ImGui.PopID();}if(plugin.Configuration.Characters.Count==0)ImGui.TextWrapped("Log in to a character to add it here. Unapproved characters are remembered only on this device.");}
 internal void Tasks(){EditingText=false;Style.Title("Tasks","A few things from "+plugin.MasterName);foreach(var task in plugin.Configuration.Features.Tasks.OrderBy(t=>t.State is "completed"or"cancelled")){ImGui.PushID(task.Id);ImGui.Separator();var overdue=task.DueAtUtc is not null&&LocalState.Parse(task.DueAtUtc)<plugin.Now&&task.State is not("completed"or"cancelled");ImGui.TextColored(Style.Accent,task.Title);ImGui.TextWrapped(task.State+(overdue?" · Overdue":"")+" · "+task.Priority);ImGui.TextWrapped(task.Description);if(task.DueAtUtc is not null)ImGui.TextWrapped("Due "+LocalState.Parse(task.DueAtUtc).ToLocalTime().ToString("g"));if(task.ReviewNote.Length>0)ImGui.TextWrapped(plugin.MasterName+": "+task.ReviewNote);if(!drafts.TryGetValue(task.Id,out var draft))drafts[task.Id]=draft=new();var pending=plugin.Configuration.TaskEvents.Any(e=>e.TaskId==task.Id);draft.Receive(task,pending);var done=draft.Checks;ImGui.BeginDisabled(!plugin.SharingAllowed||pending||task.State is "completed"or"cancelled"or"submitted");for(var i=0;i<done.Count;i++){var value=done[i];ImGui.PushID(i);if(ImGui.Checkbox(task.Checklist[i].Text+"###taskcheck",ref value))done[i]=value;ImGui.PopID();}var comment=draft.Comment;ImGui.InputTextMultiline("Your note",ref comment,1000,new Vector2(-1,65));EditingText|=ImGui.IsItemActive();draft.Comment=comment;ImGui.BeginDisabled(!plugin.SharingAllowed||pending||task.State is "completed"or"cancelled"or"submitted");if(ImGui.Button("Start task"))plugin.TaskRespond(task,"in-progress",comment,done);ImGui.SameLine();if(ImGui.Button(task.RequireReview?"Submit for review":"Complete"))plugin.TaskRespond(task,"submitted",comment,done);ImGui.SameLine();if(ImGui.Button("Decline"))plugin.TaskRespond(task,"declined",comment,done);ImGui.EndDisabled();if(plugin.Configuration.TaskEvents.Any(e=>e.TaskId==task.Id))draft.Submitted();ImGui.EndDisabled();ImGui.PopID();}if(plugin.Configuration.Features.Tasks.Count==0)ImGui.TextColored(Style.Muted,"Nothing waiting here.");}
 public void Dispose()=>portrait.Dispose();
}
