using System.Text.Json;
namespace PetService.Core;
public sealed class CharacterAccess {public string Id{get;set;}="";public string Name{get;set;}="";public string HomeWorld{get;set;}="";public bool Allowed{get;set;}}
public sealed class MasterIdentity {public string DisplayName{get;set;}="";public bool UseName{get;set;}public string PortraitRevision{get;set;}="";public string Theme{get;set;}="#baa0ff";[System.Text.Json.Serialization.JsonIgnore][Newtonsoft.Json.JsonIgnore]public string Name=>UseName&&!string.IsNullOrWhiteSpace(DisplayName)?DisplayName:"Master";}
public sealed class ResponseOptions {public string? Revision{get;set;}public List<ResponseOption> Options{get;set;}=[];public bool AllowReply{get;set;}public bool ReplyResolves{get;set;}=true;[System.Text.Json.Serialization.JsonIgnore][Newtonsoft.Json.JsonIgnore]public bool Usable=>AllowReply||Options.Any(o=>o.Action is "complete" or "decline" or "response");}
public sealed class ResponseOption {public string Id{get;set;}=Guid.NewGuid().ToString();public string Label{get;set;}="";public string Text{get;set;}="";public string Action{get;set;}="complete";public int? Minutes{get;set;}public bool Resolves{get;set;}=true;}
public sealed class Presence {public string State{get;set;}="waiting";public string CharacterId{get;set;}="";public string? UpdatedAtUtc{get;set;}}
public sealed class GameplayLock {public string Id{get;set;}="";public bool Enabled{get;set;}public string State{get;set;}="queued";public string? ExpiresAtUtc{get;set;}public string Detail{get;set;}="";}
public sealed class InventorySnapshot {[System.Text.Json.Serialization.JsonIgnore(Condition=System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]public bool Loaded{get;set;}=true;public string CharacterId{get;set;}="";public string CharacterName{get;set;}="";public string HomeWorld{get;set;}="";public string CapturedAtUtc{get;set;}="";public uint Gil{get;set;}public List<InventoryBag> Containers{get;set;}=[];}
public sealed class InventoryBag {public string? CapturedAtUtc{get;set;}public string Id{get;set;}="";public string Name{get;set;}="";public bool Available{get;set;}public int Capacity{get;set;}public List<InventorySlot> Slots{get;set;}=[];}
public sealed class InventorySlot {public int Slot{get;set;}public uint ItemId{get;set;}public string Name{get;set;}="";public uint Quantity{get;set;}public bool Hq{get;set;}public uint IconId{get;set;}}
public sealed class IconAsset {public uint IconId{get;set;}public string Png{get;set;}="";}
public sealed class ControlHistoryPage {public List<ControlEvent> Records{get;set;}=[];public string? NextCursor{get;set;}}
public sealed class ControlEvent {public string Id{get;set;}="";public string CommandId{get;set;}="";public string Kind{get;set;}="";public string Operation{get;set;}="";public string State{get;set;}="";public string AtUtc{get;set;}="";public string Detail{get;set;}="";public int DurationMinutes{get;set;}public string? ExpiresAtUtc{get;set;}}
public sealed class FeatureResult {public string? AtUtc{get;set;}public string Id{get;set;}="";public string State{get;set;}="";public string Detail{get;set;}="";}
public sealed class IntegrationCommand {public long Order{get;set;}public string RequestedAtUtc{get;set;}="";public string Id{get;set;}="";public string Kind{get;set;}="";public string CharacterId{get;set;}="";public string Operation{get;set;}="";public string Title{get;set;}="";public string Preset{get;set;}="";public string StatusId{get;set;}="";public string Colour{get;set;}="#ffffff";public string Glow{get;set;}="";public bool Prefix{get;set;}public int DurationMinutes{get;set;}public int? Stacks{get;set;}public string State{get;set;}="queued";public string? ExpiresAtUtc{get;set;}public string Detail{get;set;}="";}
public sealed class PetTask {public string? Revision{get;set;}public string Id{get;set;}="";public string Title{get;set;}="";public string Description{get;set;}="";public string State{get;set;}="pending";public string Priority{get;set;}="normal";public string Repeat{get;set;}="none";public string TimeZone{get;set;}="";public bool RequireReview{get;set;}public string? DueAtUtc{get;set;}public string Comment{get;set;}="";public string ReviewNote{get;set;}="";public List<TaskCheck> Checklist{get;set;}=[];public List<TaskHistory> History{get;set;}=[];}
public sealed class TaskCheck{public string Text{get;set;}="";public bool Done{get;set;}}
public sealed class TaskHistory{public string State{get;set;}="";public string Comment{get;set;}="";public string AtUtc{get;set;}="";}
public sealed class TaskEvent{public string? Revision{get;set;}public string Id{get;set;}=Guid.NewGuid().ToString();public string TaskId{get;set;}="";public string State{get;set;}="";public string Comment{get;set;}="";public List<bool> Checklist{get;set;}=[];}
public sealed class FeatureState {public Dictionary<string,string> SnapshotIssues{get;set;}=[];public List<ControlEvent> ControlHistory{get;set;}=[];public string? ControlHistoryCursor{get;set;}public List<uint> MissingIconIds{get;set;}=[];public List<uint> AcceptedIconIds{get;set;}=[];public List<uint> RejectedIconIds{get;set;}=[];public List<UploadRejection> RejectedResults{get;set;}=[];public bool Allowed{get;set;}public MasterIdentity Identity{get;set;}=new();public Presence Presence{get;set;}=new();public List<CharacterAccess> Characters{get;set;}=[];public GameplayLock? Lock{get;set;}public List<InventorySnapshot> Inventory{get;set;}=[];[Newtonsoft.Json.JsonConverter(typeof(JsonElementStorageConverter))]public JsonElement? InventoryRequest{get;set;}[Newtonsoft.Json.JsonProperty(ItemConverterType=typeof(JsonElementStorageConverter))]public List<JsonElement> Catalogs{get;set;}=[];[Newtonsoft.Json.JsonConverter(typeof(JsonElementStorageConverter))]public JsonElement? Catalog{get;set;}public List<IntegrationCommand> IntegrationCommands{get;set;}=[];public List<PetTask> Tasks{get;set;}=[];public RewardLedger Rewards{get;set;}=new();public List<string> AcceptedResultIds{get;set;}=[];public List<string> AcceptedTaskEventIds{get;set;}=[];public List<UploadRejection> RejectedTaskEvents{get;set;}=[];}
public sealed class RewardLedger {public bool Enabled{get;set;}public int Balance{get;set;}public List<RewardEntry> Entries{get;set;}=[];}
public sealed class RewardEntry {public int Points{get;set;}public string Note{get;set;}="";public string AtUtc{get;set;}="";}
public sealed class UploadRejection{public string? State{get;set;}public string Id{get;set;}="";public string Code{get;set;}="";public bool Retryable{get;set;}}
public sealed class RecoveryRecord{public string Id{get;set;}="";public string Kind{get;set;}="";public string Code{get;set;}="";public string Payload{get;set;}="";public string PetId{get;set;}="";}
public sealed class CredentialState{public long AccessRevision{get;set;}public bool Active{get;set;}public string PetId{get;set;}="";}
